  <!-- extends me permet de recuperer le layout que j'avais crèè, c'est a dire le navbar,sidebar etc -->
  @extends('admin.layout')

  @section('content')
         <!--statistiques-->
     
        <div class="relative before:absolute before:w-full before:h-full before:inset-0 before:bg-black before:opacity-60 before:z-10">
      <img src="https://readymadeui.com/cardImg.webp" alt="Banner Image" class="absolute inset-0 w-full h-full object-cover" />
      <div class="px-6 py-16">
        <div class="relative z-50 h-full max-w-6xl mx-auto flex flex-col justify-center items-center text-center">
          <h2 class="text-4xl font-semibold mb-20 text-center text-white">Application Metrics</h2>
          <div class="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
            <div class="text-center">
              <h3 class="text-white text-4xl font-semibold">{{ $totalUsers }}</h3>
              <div class="mt-6">
                <h6 class="text-base text-white font-medium">Total Users</h6>
                <p class="leading-relaxed text-[15px] text-slate-300 mt-3">The total number of registered users on the platform.</p>
              </div>
            </div>
            <div class="text-center">
              <h3 class="text-white text-4xl font-semibold">{{ $totalAnnonces }}</h3>
              <div class="mt-6">
                <h6 class="text-base text-white font-medium">Total Ads</h6>
                <p class="leading-relaxed text-[15px] text-slate-300 mt-3">The total ads generated by the application.</p>
              </div>
            </div>
            <div class="text-center">
              <h3 class="text-white text-4xl font-semibold">{{ $totalCategories }}</h3>
              <div class="mt-6">
                <h6 class="text-base text-white font-medium">Total Categories</h6>
                <p class="leading-relaxed text-[15px] text-slate-300 mt-3">The total Categories generated by the application.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  @endsection

    
                    
       

            

        
            